services:
  app:
    build:
      context: .
      dockerfile: Dockerfile

    environment:
      - PYTHONPATH=/app
      - PYTHONUNBUFFERED=1

    volumes:
      - .:/app

    depends_on:
      raydium_microservice:
        condition: service_healthy

    restart: on-failure
  
  raydium_microservice:
    build:
      context: .
      dockerfile: Dockerfile.ts
    
    ports:
      - 50052:5051
    
    volumes:
      - ./ts:/app

    env_file:
      - .env
    # command: curl --help

    healthcheck:
      test: nc -z -w 1 127.0.0.1 50051
      interval: 30s
      timeout: 3s
      retries: 7
      start_period: 7s
