services:
  app:
    build:
      context: .
      dockerfile: Dockerfile

    environment:
      - PYTHONPATH=/app
      - PYTHONUNBUFFERED=1

    volumes:
      - .:/app

    env_file:
      - .env

    depends_on:
      raydium_microservice:
        condition: service_healthy

    restart: on-failure
  
  raydium_microservice:
    build:
      context: .
      dockerfile: Dockerfile.ts
    
    ports:
      - 50055:5051

    env_file:
      - .env

    volumes:
      - ./ts/trade_utils.ts:/app/trade_utils.ts

    healthcheck:
      test: nc -z -w 1 127.0.0.1 50051
      interval: 30s
      timeout: 3s
      retries: 7
      start_period: 7s
