// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.2.0
//   protoc               v5.27.3
// source: pools.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";
import {
  type CallOptions,
  ChannelCredentials,
  Client,
  type ClientOptions,
  type ClientUnaryCall,
  type handleUnaryCall,
  makeGenericClientConstructor,
  Metadata,
  type ServiceError,
  type UntypedServiceImplementation,
} from "@grpc/grpc-js";

export const protobufPackage = "";

export interface ResponsePoolState {
  baseDecimal: number;
  quoteDecimal: number;
  baseTokenAmount: string;
  quoteTokenAmount: string;
  baseTokenAddress: string;
  quoteTokenAddress: string;
  baseMint: string;
  quoteMint: string;
}

export interface ErrorMesssage {
  error: string;
}

export interface RequestPoolState {
  poolData: Uint8Array;
}

export interface ResponsePoolStateOperation {
  error: ErrorMesssage | undefined;
  data: ResponsePoolState | undefined;
}

function createBaseResponsePoolState(): ResponsePoolState {
  return {
    baseDecimal: 0,
    quoteDecimal: 0,
    baseTokenAmount: "",
    quoteTokenAmount: "",
    baseTokenAddress: "",
    quoteTokenAddress: "",
    baseMint: "",
    quoteMint: "",
  };
}

export const ResponsePoolState: MessageFns<ResponsePoolState> = {
  encode(message: ResponsePoolState, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.baseDecimal !== 0) {
      writer.uint32(8).int32(message.baseDecimal);
    }
    if (message.quoteDecimal !== 0) {
      writer.uint32(16).int32(message.quoteDecimal);
    }
    if (message.baseTokenAmount !== "") {
      writer.uint32(26).string(message.baseTokenAmount);
    }
    if (message.quoteTokenAmount !== "") {
      writer.uint32(34).string(message.quoteTokenAmount);
    }
    if (message.baseTokenAddress !== "") {
      writer.uint32(42).string(message.baseTokenAddress);
    }
    if (message.quoteTokenAddress !== "") {
      writer.uint32(50).string(message.quoteTokenAddress);
    }
    if (message.baseMint !== "") {
      writer.uint32(58).string(message.baseMint);
    }
    if (message.quoteMint !== "") {
      writer.uint32(66).string(message.quoteMint);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ResponsePoolState {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseResponsePoolState();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag !== 8) {
            break;
          }

          message.baseDecimal = reader.int32();
          continue;
        case 2:
          if (tag !== 16) {
            break;
          }

          message.quoteDecimal = reader.int32();
          continue;
        case 3:
          if (tag !== 26) {
            break;
          }

          message.baseTokenAmount = reader.string();
          continue;
        case 4:
          if (tag !== 34) {
            break;
          }

          message.quoteTokenAmount = reader.string();
          continue;
        case 5:
          if (tag !== 42) {
            break;
          }

          message.baseTokenAddress = reader.string();
          continue;
        case 6:
          if (tag !== 50) {
            break;
          }

          message.quoteTokenAddress = reader.string();
          continue;
        case 7:
          if (tag !== 58) {
            break;
          }

          message.baseMint = reader.string();
          continue;
        case 8:
          if (tag !== 66) {
            break;
          }

          message.quoteMint = reader.string();
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): ResponsePoolState {
    return {
      baseDecimal: isSet(object.baseDecimal) ? globalThis.Number(object.baseDecimal) : 0,
      quoteDecimal: isSet(object.quoteDecimal) ? globalThis.Number(object.quoteDecimal) : 0,
      baseTokenAmount: isSet(object.baseTokenAmount) ? globalThis.String(object.baseTokenAmount) : "",
      quoteTokenAmount: isSet(object.quoteTokenAmount) ? globalThis.String(object.quoteTokenAmount) : "",
      baseTokenAddress: isSet(object.baseTokenAddress) ? globalThis.String(object.baseTokenAddress) : "",
      quoteTokenAddress: isSet(object.quoteTokenAddress) ? globalThis.String(object.quoteTokenAddress) : "",
      baseMint: isSet(object.baseMint) ? globalThis.String(object.baseMint) : "",
      quoteMint: isSet(object.quoteMint) ? globalThis.String(object.quoteMint) : "",
    };
  },

  toJSON(message: ResponsePoolState): unknown {
    const obj: any = {};
    if (message.baseDecimal !== 0) {
      obj.baseDecimal = Math.round(message.baseDecimal);
    }
    if (message.quoteDecimal !== 0) {
      obj.quoteDecimal = Math.round(message.quoteDecimal);
    }
    if (message.baseTokenAmount !== "") {
      obj.baseTokenAmount = message.baseTokenAmount;
    }
    if (message.quoteTokenAmount !== "") {
      obj.quoteTokenAmount = message.quoteTokenAmount;
    }
    if (message.baseTokenAddress !== "") {
      obj.baseTokenAddress = message.baseTokenAddress;
    }
    if (message.quoteTokenAddress !== "") {
      obj.quoteTokenAddress = message.quoteTokenAddress;
    }
    if (message.baseMint !== "") {
      obj.baseMint = message.baseMint;
    }
    if (message.quoteMint !== "") {
      obj.quoteMint = message.quoteMint;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<ResponsePoolState>, I>>(base?: I): ResponsePoolState {
    return ResponsePoolState.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<ResponsePoolState>, I>>(object: I): ResponsePoolState {
    const message = createBaseResponsePoolState();
    message.baseDecimal = object.baseDecimal ?? 0;
    message.quoteDecimal = object.quoteDecimal ?? 0;
    message.baseTokenAmount = object.baseTokenAmount ?? "";
    message.quoteTokenAmount = object.quoteTokenAmount ?? "";
    message.baseTokenAddress = object.baseTokenAddress ?? "";
    message.quoteTokenAddress = object.quoteTokenAddress ?? "";
    message.baseMint = object.baseMint ?? "";
    message.quoteMint = object.quoteMint ?? "";
    return message;
  },
};

function createBaseErrorMesssage(): ErrorMesssage {
  return { error: "" };
}

export const ErrorMesssage: MessageFns<ErrorMesssage> = {
  encode(message: ErrorMesssage, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.error !== "") {
      writer.uint32(10).string(message.error);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ErrorMesssage {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseErrorMesssage();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag !== 10) {
            break;
          }

          message.error = reader.string();
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): ErrorMesssage {
    return { error: isSet(object.error) ? globalThis.String(object.error) : "" };
  },

  toJSON(message: ErrorMesssage): unknown {
    const obj: any = {};
    if (message.error !== "") {
      obj.error = message.error;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<ErrorMesssage>, I>>(base?: I): ErrorMesssage {
    return ErrorMesssage.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<ErrorMesssage>, I>>(object: I): ErrorMesssage {
    const message = createBaseErrorMesssage();
    message.error = object.error ?? "";
    return message;
  },
};

function createBaseRequestPoolState(): RequestPoolState {
  return { poolData: new Uint8Array(0) };
}

export const RequestPoolState: MessageFns<RequestPoolState> = {
  encode(message: RequestPoolState, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.poolData.length !== 0) {
      writer.uint32(10).bytes(message.poolData);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): RequestPoolState {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseRequestPoolState();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag !== 10) {
            break;
          }

          message.poolData = reader.bytes();
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): RequestPoolState {
    return { poolData: isSet(object.poolData) ? bytesFromBase64(object.poolData) : new Uint8Array(0) };
  },

  toJSON(message: RequestPoolState): unknown {
    const obj: any = {};
    if (message.poolData.length !== 0) {
      obj.poolData = base64FromBytes(message.poolData);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<RequestPoolState>, I>>(base?: I): RequestPoolState {
    return RequestPoolState.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<RequestPoolState>, I>>(object: I): RequestPoolState {
    const message = createBaseRequestPoolState();
    message.poolData = object.poolData ?? new Uint8Array(0);
    return message;
  },
};

function createBaseResponsePoolStateOperation(): ResponsePoolStateOperation {
  return { error: undefined, data: undefined };
}

export const ResponsePoolStateOperation: MessageFns<ResponsePoolStateOperation> = {
  encode(message: ResponsePoolStateOperation, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.error !== undefined) {
      ErrorMesssage.encode(message.error, writer.uint32(10).fork()).join();
    }
    if (message.data !== undefined) {
      ResponsePoolState.encode(message.data, writer.uint32(18).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ResponsePoolStateOperation {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseResponsePoolStateOperation();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag !== 10) {
            break;
          }

          message.error = ErrorMesssage.decode(reader, reader.uint32());
          continue;
        case 2:
          if (tag !== 18) {
            break;
          }

          message.data = ResponsePoolState.decode(reader, reader.uint32());
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): ResponsePoolStateOperation {
    return {
      error: isSet(object.error) ? ErrorMesssage.fromJSON(object.error) : undefined,
      data: isSet(object.data) ? ResponsePoolState.fromJSON(object.data) : undefined,
    };
  },

  toJSON(message: ResponsePoolStateOperation): unknown {
    const obj: any = {};
    if (message.error !== undefined) {
      obj.error = ErrorMesssage.toJSON(message.error);
    }
    if (message.data !== undefined) {
      obj.data = ResponsePoolState.toJSON(message.data);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<ResponsePoolStateOperation>, I>>(base?: I): ResponsePoolStateOperation {
    return ResponsePoolStateOperation.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<ResponsePoolStateOperation>, I>>(object: I): ResponsePoolStateOperation {
    const message = createBaseResponsePoolStateOperation();
    message.error = (object.error !== undefined && object.error !== null)
      ? ErrorMesssage.fromPartial(object.error)
      : undefined;
    message.data = (object.data !== undefined && object.data !== null)
      ? ResponsePoolState.fromPartial(object.data)
      : undefined;
    return message;
  },
};

export type PoolStateService = typeof PoolStateService;
export const PoolStateService = {
  getPoolState: {
    path: "/PoolState/getPoolState",
    requestStream: false,
    responseStream: false,
    requestSerialize: (value: RequestPoolState) => Buffer.from(RequestPoolState.encode(value).finish()),
    requestDeserialize: (value: Buffer) => RequestPoolState.decode(value),
    responseSerialize: (value: ResponsePoolStateOperation) =>
      Buffer.from(ResponsePoolStateOperation.encode(value).finish()),
    responseDeserialize: (value: Buffer) => ResponsePoolStateOperation.decode(value),
  },
} as const;

export interface PoolStateServer extends UntypedServiceImplementation {
  getPoolState: handleUnaryCall<RequestPoolState, ResponsePoolStateOperation>;
}

export interface PoolStateClient extends Client {
  getPoolState(
    request: RequestPoolState,
    callback: (error: ServiceError | null, response: ResponsePoolStateOperation) => void,
  ): ClientUnaryCall;
  getPoolState(
    request: RequestPoolState,
    metadata: Metadata,
    callback: (error: ServiceError | null, response: ResponsePoolStateOperation) => void,
  ): ClientUnaryCall;
  getPoolState(
    request: RequestPoolState,
    metadata: Metadata,
    options: Partial<CallOptions>,
    callback: (error: ServiceError | null, response: ResponsePoolStateOperation) => void,
  ): ClientUnaryCall;
}

export const PoolStateClient = makeGenericClientConstructor(PoolStateService, "PoolState") as unknown as {
  new (address: string, credentials: ChannelCredentials, options?: Partial<ClientOptions>): PoolStateClient;
  service: typeof PoolStateService;
  serviceName: string;
};

function bytesFromBase64(b64: string): Uint8Array {
  if ((globalThis as any).Buffer) {
    return Uint8Array.from(globalThis.Buffer.from(b64, "base64"));
  } else {
    const bin = globalThis.atob(b64);
    const arr = new Uint8Array(bin.length);
    for (let i = 0; i < bin.length; ++i) {
      arr[i] = bin.charCodeAt(i);
    }
    return arr;
  }
}

function base64FromBytes(arr: Uint8Array): string {
  if ((globalThis as any).Buffer) {
    return globalThis.Buffer.from(arr).toString("base64");
  } else {
    const bin: string[] = [];
    arr.forEach((byte) => {
      bin.push(globalThis.String.fromCharCode(byte));
    });
    return globalThis.btoa(bin.join(""));
  }
}

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T;
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T;
}
